steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_AGENT_URL=${_NEXT_PUBLIC_AGENT_URL}
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
